import fs from "fs";
import path from "path";

const projectRoot = process.cwd();
const assetsFile = path.join(projectRoot, "asset-manifest.js");

const imageDir = path.join(projectRoot, "imagini");
const videoDir = path.join(projectRoot, "video");

const imageExtensions = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const videoExtensions = new Set([".mp4", ".webm"]);

function listFiles(dir, extensions) {
  try {
    return fs.readdirSync(dir)
      .filter((name) => {
        const ext = path.extname(name).toLowerCase();
        return extensions.has(ext);
      })
      .sort();
  } catch (err) {
    return [];
  }
}

const images = listFiles(imageDir, imageExtensions).map((name) => `./imagini/${name}`);
const videos = listFiles(videoDir, videoExtensions).map((name) => `./video/${name}`);

const content = `// This file is auto-generated by scripts/generate-assets.js
// Run \"npm run dev\" or \"npm run build\" to update.

export const images = ${JSON.stringify(images, null, 2)};
export const videos = ${JSON.stringify(videos, null, 2)};
`;

fs.writeFileSync(assetsFile, content, "utf8");
console.log(`Wrote ${assetsFile} with ${images.length} images and ${videos.length} videos.`);
